---
title: "Portfolio"
author: "Ingur Veken"
date: "21/02/2021"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    orientation: columns
    theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load("anime.RDATA")

library(flexdashboard)
library(ggthemes)
library(ggplot2)
library(plotly)
library(dplyr)

theme_set(theme_hc())
```

Column
--------------------------------------------------------------------------------

> <center>PLEASE DO NOT SHOW THIS PORTFOLIO IN CLASS</center>

### **Anime Music**

Japanese animation - also known as Anime - has grown immensely as both an industry and art form over the years. Music has played a big part in this growth, as the intro and credits have always been accompanied by a song. First appearing in 1963 together with the release of Astro Boy, anime music quickly developed into a musical genre in its own right. 
Spotify released four playlists called "Anime Rewind" for every decade between the '80s and the '10s.  These playlists make up the corpus of 181 selected hit songs released during this time. My main goal is to analyze how anime music has evolved over the years, and I believe this corpus allows me to do so. 

There are multiple possible comparison points from influential artists to song features like `danceability` and `energy`/`loudness`. The corpus includes most of the popular hit songs and seems to cover the genre appropriately. The only limitations are that there are no songs from the '60s and '70s, and there might still be a few tracks left that are not included in the original playlists by Spotify.

There are multiple tracks to keep in mind, such as A Cruel Angel's Thesis (1995) and Hare Hare Yukai (2006). These tracks were not only successful but are also said to have established new styles of anime songs. 

Links to the Spotify playlists:

- [Anime Rewind '80s](https://open.spotify.com/playlist/37i9dQZF1DXcFCZS9poESZ?si=X78joBOfSNybC2_h2ywCBQ)
- [Anime Rewind '90s](https://open.spotify.com/playlist/37i9dQZF1DXanOaZVFiwtB?si=cBGaz_VxRRW14iXdNAFQ8g)
- [Anime Rewind '00s](https://open.spotify.com/playlist/37i9dQZF1DWZZu9JWZK2dy?si=wPjUpf9pSSST3NhlYnkxjQ)
- [Anime Rewind '10s](https://open.spotify.com/playlist/37i9dQZF1DWYzHfIcEruXw?si=77LFyMfiSLSIwtcEN66MHw)

Column
--------------------------------------------------------------------------------

### Danceability per decennia

```{r, echo=FALSE}
danceability_plot <- anime %>%
  ggplot(aes(category, danceability)) +
    geom_boxplot(aes(fill = category)) + 
    labs(
      # title = "Danceability per decennia",
      x = NULL,
      y = NULL
    ) + 
    theme(
      legend.position = "none"
    )

ggplotly(danceability_plot)
```
### Loudness per decennia

```{r, echo=FALSE}
loudness_plot <- anime %>%
  ggplot(aes(category, loudness)) +
    geom_boxplot(aes(fill = category)) + 
    labs(
      # title = "Loudness per decennia",
      x = NULL,
      y = NULL
    ) + 
    theme(
      legend.position = "none"
    )

ggplotly(loudness_plot)
```

